#?? ???? ?? ?? ??: ??? ??? ?? too much log??? ???? ?? ?? ??
logging:
  level.org.apache.coyote.http11=debug

#?? ?? ??
file:
  dir=C:\Users\82108\Desktop\filestore\

#??? ??? ??
spring:
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 10MB
